export type SeedAirport = {
  iata: string;
  icao: string;
  name: string;
  city: string;
  country: string;
  lat: number;
  lon: number;
  timezone?: string;
};

export type SeedAirline = {
  iata: string;
  icao: string;
  name: string;
  country: string;
  callsign?: string;
};

export const SEED_AIRPORTS: SeedAirport[] = [
  { iata: "FRA", icao: "EDDF", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany", lat: 50.0379, lon: 8.5622, timezone: "Europe/Berlin" },
  { iata: "MUC", icao: "EDDM", name: "Munich Airport", city: "Munich", country: "Germany", lat: 48.3538, lon: 11.7861, timezone: "Europe/Berlin" },
  { iata: "BER", icao: "EDDB", name: "Berlin Brandenburg", city: "Berlin", country: "Germany", lat: 52.3667, lon: 13.5033, timezone: "Europe/Berlin" },
  { iata: "HAM", icao: "EDDH", name: "Hamburg Airport", city: "Hamburg", country: "Germany", lat: 53.6304, lon: 9.98823, timezone: "Europe/Berlin" },
  { iata: "DUS", icao: "EDDL", name: "Düsseldorf Airport", city: "Düsseldorf", country: "Germany", lat: 51.2895, lon: 6.76678, timezone: "Europe/Berlin" },
  { iata: "CGN", icao: "EDDK", name: "Cologne Bonn Airport", city: "Cologne", country: "Germany", lat: 50.8659, lon: 7.14274, timezone: "Europe/Berlin" },
  { iata: "STR", icao: "EDDS", name: "Stuttgart Airport", city: "Stuttgart", country: "Germany", lat: 48.6899, lon: 9.22196, timezone: "Europe/Berlin" },
  { iata: "CDG", icao: "LFPG", name: "Charles de Gaulle", city: "Paris", country: "France", lat: 49.0097, lon: 2.54793, timezone: "Europe/Paris" },
  { iata: "ORY", icao: "LFPO", name: "Orly Airport", city: "Paris", country: "France", lat: 48.7233, lon: 2.37944, timezone: "Europe/Paris" },
  { iata: "LYS", icao: "LFLL", name: "Lyon-Saint Exupéry", city: "Lyon", country: "France", lat: 45.7256, lon: 5.08111, timezone: "Europe/Paris" },
  { iata: "AMS", icao: "EHAM", name: "Amsterdam Schiphol", city: "Amsterdam", country: "Netherlands", lat: 52.3086, lon: 4.76389, timezone: "Europe/Amsterdam" },
  { iata: "BRU", icao: "EBBR", name: "Brussels Airport", city: "Brussels", country: "Belgium", lat: 50.9014, lon: 4.48444, timezone: "Europe/Brussels" },
  { iata: "LHR", icao: "EGLL", name: "Heathrow", city: "London", country: "United Kingdom", lat: 51.47, lon: -0.4543, timezone: "Europe/London" },
  { iata: "LGW", icao: "EGKK", name: "Gatwick", city: "London", country: "United Kingdom", lat: 51.1481, lon: -0.190278, timezone: "Europe/London" },
  { iata: "MAN", icao: "EGCC", name: "Manchester Airport", city: "Manchester", country: "United Kingdom", lat: 53.3537, lon: -2.27495, timezone: "Europe/London" },
  { iata: "DUB", icao: "EIDW", name: "Dublin Airport", city: "Dublin", country: "Ireland", lat: 53.4213, lon: -6.27007, timezone: "Europe/Dublin" },
  { iata: "MAD", icao: "LEMD", name: "Adolfo Suárez Madrid-Barajas", city: "Madrid", country: "Spain", lat: 40.4719, lon: -3.56264, timezone: "Europe/Madrid" },
  { iata: "BCN", icao: "LEBL", name: "Barcelona-El Prat", city: "Barcelona", country: "Spain", lat: 41.2971, lon: 2.07846, timezone: "Europe/Madrid" },
  { iata: "LIS", icao: "LPPT", name: "Humberto Delgado", city: "Lisbon", country: "Portugal", lat: 38.7813, lon: -9.13592, timezone: "Europe/Lisbon" },
  { iata: "OPO", icao: "LPPR", name: "Francisco Sá Carneiro", city: "Porto", country: "Portugal", lat: 41.2481, lon: -8.68139, timezone: "Europe/Lisbon" },
  { iata: "FCO", icao: "LIRF", name: "Leonardo da Vinci–Fiumicino", city: "Rome", country: "Italy", lat: 41.8003, lon: 12.2389, timezone: "Europe/Rome" },
  { iata: "MXP", icao: "LIMC", name: "Malpensa", city: "Milan", country: "Italy", lat: 45.6306, lon: 8.72811, timezone: "Europe/Rome" },
  { iata: "LIN", icao: "LIML", name: "Linate", city: "Milan", country: "Italy", lat: 45.4451, lon: 9.27674, timezone: "Europe/Rome" },
  { iata: "VCE", icao: "LIPZ", name: "Venice Marco Polo", city: "Venice", country: "Italy", lat: 45.5053, lon: 12.3519, timezone: "Europe/Rome" },
  { iata: "ZRH", icao: "LSZH", name: "Zurich Airport", city: "Zurich", country: "Switzerland", lat: 47.4647, lon: 8.54917, timezone: "Europe/Zurich" },
  { iata: "GVA", icao: "LSGG", name: "Geneva Airport", city: "Geneva", country: "Switzerland", lat: 46.2381, lon: 6.10895, timezone: "Europe/Zurich" },
  { iata: "VIE", icao: "LOWW", name: "Vienna International", city: "Vienna", country: "Austria", lat: 48.1103, lon: 16.5697, timezone: "Europe/Vienna" },
  { iata: "CPH", icao: "EKCH", name: "Copenhagen Kastrup", city: "Copenhagen", country: "Denmark", lat: 55.6179, lon: 12.656, timezone: "Europe/Copenhagen" },
  { iata: "ARN", icao: "ESSA", name: "Stockholm Arlanda", city: "Stockholm", country: "Sweden", lat: 59.6519, lon: 17.9186, timezone: "Europe/Stockholm" },
  { iata: "OSL", icao: "ENGM", name: "Oslo Gardermoen", city: "Oslo", country: "Norway", lat: 60.1939, lon: 11.1004, timezone: "Europe/Oslo" },
  { iata: "HEL", icao: "EFHK", name: "Helsinki-Vantaa", city: "Helsinki", country: "Finland", lat: 60.3172, lon: 24.9633, timezone: "Europe/Helsinki" },
  { iata: "WAW", icao: "EPWA", name: "Warsaw Chopin", city: "Warsaw", country: "Poland", lat: 52.1657, lon: 20.9671, timezone: "Europe/Warsaw" },
  { iata: "PRG", icao: "LKPR", name: "Václav Havel Prague", city: "Prague", country: "Czechia", lat: 50.1008, lon: 14.26, timezone: "Europe/Prague" },
  { iata: "BUD", icao: "LHBP", name: "Budapest Ferenc Liszt", city: "Budapest", country: "Hungary", lat: 47.4369, lon: 19.2556, timezone: "Europe/Budapest" },
  { iata: "ATH", icao: "LGAV", name: "Athens International", city: "Athens", country: "Greece", lat: 37.9364, lon: 23.9445, timezone: "Europe/Athens" },
  { iata: "IST", icao: "LTFM", name: "Istanbul Airport", city: "Istanbul", country: "Türkiye", lat: 41.2753, lon: 28.7519, timezone: "Europe/Istanbul" },
  { iata: "DXB", icao: "OMDB", name: "Dubai International", city: "Dubai", country: "United Arab Emirates", lat: 25.2528, lon: 55.3644, timezone: "Asia/Dubai" },
  { iata: "DOH", icao: "OTHH", name: "Hamad International", city: "Doha", country: "Qatar", lat: 25.2731, lon: 51.6081, timezone: "Asia/Qatar" },
  { iata: "AUH", icao: "OMAA", name: "Zayed International", city: "Abu Dhabi", country: "United Arab Emirates", lat: 24.433, lon: 54.6511, timezone: "Asia/Dubai" },
  { iata: "SIN", icao: "WSSS", name: "Singapore Changi", city: "Singapore", country: "Singapore", lat: 1.35019, lon: 103.994, timezone: "Asia/Singapore" },
  { iata: "HKG", icao: "VHHH", name: "Hong Kong International", city: "Hong Kong", country: "Hong Kong", lat: 22.3089, lon: 113.915, timezone: "Asia/Hong_Kong" },
  { iata: "NRT", icao: "RJAA", name: "Narita International", city: "Tokyo", country: "Japan", lat: 35.7647, lon: 140.386, timezone: "Asia/Tokyo" },
  { iata: "HND", icao: "RJTT", name: "Haneda", city: "Tokyo", country: "Japan", lat: 35.5523, lon: 139.78, timezone: "Asia/Tokyo" },
  { iata: "ICN", icao: "RKSI", name: "Incheon International", city: "Seoul", country: "South Korea", lat: 37.4691, lon: 126.451, timezone: "Asia/Seoul" },
  { iata: "BKK", icao: "VTBS", name: "Suvarnabhumi", city: "Bangkok", country: "Thailand", lat: 13.6811, lon: 100.747, timezone: "Asia/Bangkok" },
  { iata: "DEL", icao: "VIDP", name: "Indira Gandhi International", city: "Delhi", country: "India", lat: 28.5562, lon: 77.1000, timezone: "Asia/Kolkata" },
  { iata: "BOM", icao: "VABB", name: "Chhatrapati Shivaji Maharaj", city: "Mumbai", country: "India", lat: 19.0887, lon: 72.8679, timezone: "Asia/Kolkata" },
  { iata: "JFK", icao: "KJFK", name: "John F. Kennedy International", city: "New York", country: "United States", lat: 40.6413, lon: -73.7781, timezone: "America/New_York" },
  { iata: "EWR", icao: "KEWR", name: "Newark Liberty", city: "Newark", country: "United States", lat: 40.6895, lon: -74.1745, timezone: "America/New_York" },
  { iata: "LGA", icao: "KLGA", name: "LaGuardia", city: "New York", country: "United States", lat: 40.7769, lon: -73.874, timezone: "America/New_York" },
  { iata: "BOS", icao: "KBOS", name: "Logan International", city: "Boston", country: "United States", lat: 42.3656, lon: -71.0096, timezone: "America/New_York" },
  { iata: "IAD", icao: "KIAD", name: "Washington Dulles", city: "Washington", country: "United States", lat: 38.9531, lon: -77.4565, timezone: "America/New_York" },
  { iata: "ORD", icao: "KORD", name: "O'Hare International", city: "Chicago", country: "United States", lat: 41.9742, lon: -87.9073, timezone: "America/Chicago" },
  { iata: "ATL", icao: "KATL", name: "Hartsfield-Jackson", city: "Atlanta", country: "United States", lat: 33.6407, lon: -84.4277, timezone: "America/New_York" },
  { iata: "MIA", icao: "KMIA", name: "Miami International", city: "Miami", country: "United States", lat: 25.7959, lon: -80.287, timezone: "America/New_York" },
  { iata: "DFW", icao: "KDFW", name: "Dallas/Fort Worth", city: "Dallas", country: "United States", lat: 32.8998, lon: -97.0403, timezone: "America/Chicago" },
  { iata: "LAX", icao: "KLAX", name: "Los Angeles International", city: "Los Angeles", country: "United States", lat: 33.9416, lon: -118.409, timezone: "America/Los_Angeles" },
  { iata: "SFO", icao: "KSFO", name: "San Francisco International", city: "San Francisco", country: "United States", lat: 37.6213, lon: -122.379, timezone: "America/Los_Angeles" },
  { iata: "SEA", icao: "KSEA", name: "Seattle-Tacoma", city: "Seattle", country: "United States", lat: 47.4502, lon: -122.309, timezone: "America/Los_Angeles" },
  { iata: "DEN", icao: "KDEN", name: "Denver International", city: "Denver", country: "United States", lat: 39.8561, lon: -104.674, timezone: "America/Denver" },
  { iata: "YYZ", icao: "CYYZ", name: "Toronto Pearson", city: "Toronto", country: "Canada", lat: 43.6777, lon: -79.6248, timezone: "America/Toronto" },
  { iata: "YVR", icao: "CYVR", name: "Vancouver International", city: "Vancouver", country: "Canada", lat: 49.1967, lon: -123.182, timezone: "America/Vancouver" },
  { iata: "MEX", icao: "MMMX", name: "Mexico City International", city: "Mexico City", country: "Mexico", lat: 19.4363, lon: -99.0721, timezone: "America/Mexico_City" },
  { iata: "GRU", icao: "SBGR", name: "São Paulo–Guarulhos", city: "São Paulo", country: "Brazil", lat: -23.4356, lon: -46.4731, timezone: "America/Sao_Paulo" },
  { iata: "EZE", icao: "SAEZ", name: "Ministro Pistarini", city: "Buenos Aires", country: "Argentina", lat: -34.8222, lon: -58.5358, timezone: "America/Argentina/Buenos_Aires" },
  { iata: "SYD", icao: "YSSY", name: "Sydney Kingsford Smith", city: "Sydney", country: "Australia", lat: -33.9399, lon: 151.175, timezone: "Australia/Sydney" },
  { iata: "MEL", icao: "YMML", name: "Melbourne Airport", city: "Melbourne", country: "Australia", lat: -37.669, lon: 144.841, timezone: "Australia/Melbourne" },
  { iata: "AKL", icao: "NZAA", name: "Auckland Airport", city: "Auckland", country: "New Zealand", lat: -37.0082, lon: 174.785, timezone: "Pacific/Auckland" },
  { iata: "JNB", icao: "FAOR", name: "O. R. Tambo", city: "Johannesburg", country: "South Africa", lat: -26.1392, lon: 28.246, timezone: "Africa/Johannesburg" },
  { iata: "CPT", icao: "FACT", name: "Cape Town International", city: "Cape Town", country: "South Africa", lat: -33.9648, lon: 18.6017, timezone: "Africa/Johannesburg" },
  { iata: "CAI", icao: "HECA", name: "Cairo International", city: "Cairo", country: "Egypt", lat: 30.1219, lon: 31.4056, timezone: "Africa/Cairo" },
];

export const SEED_AIRLINES: SeedAirline[] = [
  { iata: "LH", icao: "DLH", name: "Lufthansa", country: "Germany", callsign: "LUFTHANSA" },
  { iata: "AF", icao: "AFR", name: "Air France", country: "France", callsign: "AIRFRANS" },
  { iata: "BA", icao: "BAW", name: "British Airways", country: "United Kingdom", callsign: "SPEEDBIRD" },
  { iata: "KL", icao: "KLM", name: "KLM", country: "Netherlands", callsign: "KLM" },
  { iata: "LX", icao: "SWR", name: "SWISS", country: "Switzerland", callsign: "SWISS" },
  { iata: "OS", icao: "AUA", name: "Austrian Airlines", country: "Austria", callsign: "AUSTRIAN" },
  { iata: "SN", icao: "BEL", name: "Brussels Airlines", country: "Belgium", callsign: "BEE-LINE" },
  { iata: "IB", icao: "IBE", name: "Iberia", country: "Spain", callsign: "IBERIA" },
  { iata: "TP", icao: "TAP", name: "TAP Air Portugal", country: "Portugal", callsign: "AIR PORTUGAL" },
  { iata: "AZ", icao: "ITY", name: "ITA Airways", country: "Italy", callsign: "ITARROW" },
  { iata: "AY", icao: "FIN", name: "Finnair", country: "Finland", callsign: "FINNAIR" },
  { iata: "SK", icao: "SAS", name: "SAS", country: "Sweden", callsign: "SCANDINAVIAN" },
  { iata: "DY", icao: "NAX", name: "Norwegian", country: "Norway", callsign: "NOR SHUTTLE" },
  { iata: "FR", icao: "RYR", name: "Ryanair", country: "Ireland", callsign: "RYANAIR" },
  { iata: "U2", icao: "EZY", name: "easyJet", country: "United Kingdom", callsign: "EASY" },
  { iata: "W6", icao: "WZZ", name: "Wizz Air", country: "Hungary", callsign: "WIZZAIR" },
  { iata: "EK", icao: "UAE", name: "Emirates", country: "United Arab Emirates", callsign: "EMIRATES" },
  { iata: "QR", icao: "QTR", name: "Qatar Airways", country: "Qatar", callsign: "QATARI" },
  { iata: "EY", icao: "ETD", name: "Etihad Airways", country: "United Arab Emirates", callsign: "ETIHAD" },
  { iata: "TK", icao: "THY", name: "Turkish Airlines", country: "Türkiye", callsign: "TURKISH" },
  { iata: "SQ", icao: "SIA", name: "Singapore Airlines", country: "Singapore", callsign: "SINGAPORE" },
  { iata: "CX", icao: "CPA", name: "Cathay Pacific", country: "Hong Kong", callsign: "CATHAY" },
  { iata: "NH", icao: "ANA", name: "All Nippon Airways", country: "Japan", callsign: "ALL NIPPON" },
  { iata: "JL", icao: "JAL", name: "Japan Airlines", country: "Japan", callsign: "JAPANAIR" },
  { iata: "KE", icao: "KAL", name: "Korean Air", country: "South Korea", callsign: "KOREANAIR" },
  { iata: "AA", icao: "AAL", name: "American Airlines", country: "United States", callsign: "AMERICAN" },
  { iata: "DL", icao: "DAL", name: "Delta Air Lines", country: "United States", callsign: "DELTA" },
  { iata: "UA", icao: "UAL", name: "United Airlines", country: "United States", callsign: "UNITED" },
  { iata: "WN", icao: "SWA", name: "Southwest Airlines", country: "United States", callsign: "SOUTHWEST" },
  { iata: "B6", icao: "JBU", name: "JetBlue", country: "United States", callsign: "JETBLUE" },
  { iata: "AS", icao: "ASA", name: "Alaska Airlines", country: "United States", callsign: "ALASKA" },
  { iata: "AC", icao: "ACA", name: "Air Canada", country: "Canada", callsign: "AIR CANADA" },
  { iata: "QF", icao: "QFA", name: "Qantas", country: "Australia", callsign: "QANTAS" },
  { iata: "LA", icao: "LAN", name: "LATAM", country: "Chile", callsign: "LAN" },
  { iata: "ET", icao: "ETH", name: "Ethiopian Airlines", country: "Ethiopia", callsign: "ETHIOPIAN" },
];

export const SEED_ROUTES: { airlineIata: string; fromIata: string; toIata: string }[] = [
  { airlineIata: "LH", fromIata: "FRA", toIata: "JFK" },
  { airlineIata: "LH", fromIata: "MUC", toIata: "JFK" },
  { airlineIata: "LH", fromIata: "FRA", toIata: "SFO" },
  { airlineIata: "LH", fromIata: "FRA", toIata: "LAX" },
  { airlineIata: "LH", fromIata: "FRA", toIata: "LHR" },
  { airlineIata: "AF", fromIata: "CDG", toIata: "LIS" },
  { airlineIata: "AF", fromIata: "CDG", toIata: "JFK" },
  { airlineIata: "BA", fromIata: "LHR", toIata: "BER" },
  { airlineIata: "BA", fromIata: "LHR", toIata: "JFK" },
  { airlineIata: "KL", fromIata: "AMS", toIata: "JFK" },
  { airlineIata: "LX", fromIata: "ZRH", toIata: "JFK" },
  { airlineIata: "TP", fromIata: "LIS", toIata: "JFK" },
  { airlineIata: "EK", fromIata: "DXB", toIata: "FRA" },
  { airlineIata: "QR", fromIata: "DOH", toIata: "FRA" },
];
